### ISSUE TITLE
Restructure commands.

### ISSUE THREAD

**Issue by Otis0620** [osu-cascades/hackbot#27]
The methods in the Command class are available to the user. They can access them by prefixing the message followed by the method name. It would best practice to structure the code in a way so this is not possible.

**Comment by ctsstc** [comment]
If we went with TypeScript (or something similar) we could use an interface, which would give us more of a "plugin" system where people had to implement specific methods/properties on their extended class. 

One of the requirements would be that it would have to provide a list of commands that the plugin implemented. Then an overall collector could validate that each command is unique, otherwise, it could reject it or namespace it, ie: `plugin-name.command`

Another quicker option with TS could be to just use it and have private/public methods, but I'm not sure that will prevent the user's input still as I have not dug into the parser too much yet.
